# Generated by Django 5.1.4 on 2024-12-31 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_area_alter_project_contractual_tonnage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Building Name')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='core.project')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_designation', models.CharField(max_length=100, verbose_name='Log Designation')),
                ('part_designation', models.CharField(max_length=100, verbose_name='Part Designation')),
                ('assembly_mark', models.CharField(max_length=100, verbose_name='Assembly Mark')),
                ('sub_assembly_mark', models.CharField(blank=True, max_length=100, verbose_name='Sub-Assembly Mark')),
                ('part_mark', models.CharField(max_length=100, verbose_name='Part Mark')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('profile', models.CharField(max_length=100, verbose_name='Profile')),
                ('grade', models.CharField(max_length=50, verbose_name='Grade')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Length (mm)')),
                ('net_area_single', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Area (m²) for one')),
                ('net_area_all', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Area (m²) for all')),
                ('single_part_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Single Part Weight')),
                ('net_weight_all', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Weight (kg) for all')),
                ('revision_number', models.CharField(max_length=20, verbose_name='Revision #')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='core.building')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='core.project')),
            ],
            options={
                'verbose_name': 'Raw Data',
                'verbose_name_plural': 'Raw Data',
                'ordering': ['project', 'building', 'assembly_mark', 'part_mark'],
            },
        ),
    ]
