# Generated by Django 5.1.4 on 2024-12-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_building_calculated_tonnage_building_design_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='erectable',
            field=models.BooleanField(default=True, help_text='Check if this project includes erection scope', verbose_name='Erectable'),
        ),
    ]
