# Generated by Django 5.1.4 on 2024-12-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_project_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Contract Amount'),
        ),
        migrations.AddField(
            model_name='project',
            name='down_payment_percentage',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Enter percentage (e.g., 20 for 20%)', max_digits=5, verbose_name='Down Payment %'),
        ),
        migrations.AlterField(
            model_name='building',
            name='designer_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Designer Name'),
        ),
        migrations.AlterField(
            model_name='building',
            name='subcontractor_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Subcontractor Name'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='quantity_produced',
            field=models.IntegerField(default=0, verbose_name='Quantity Produced'),
        ),
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coat_1_liters_needed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Liters Needed'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coat_1_microns',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Coat 1 - Microns'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coat_2_liters_needed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Liters Needed'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coat_2_microns',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Coat 2 - Microns'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coat_3_liters_needed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Liters Needed'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coat_3_microns',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Coat 3 - Microns'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coat_4_liters_needed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Liters Needed'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coat_4_microns',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Coat 4 - Microns'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contractual_tonnage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Contractual Tonnage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Down Payment Amount'),
        ),
        migrations.AlterField(
            model_name='project',
            name='engineering_tonnage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Engineering Tonnage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='galvanization_microns',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Galvanization Microns'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ho_retention',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='H.O Retention'),
        ),
        migrations.AlterField(
            model_name='project',
            name='m2_per_ton',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='m2/Ton'),
        ),
        migrations.AlterField(
            model_name='project',
            name='paint_coat_1',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Paint Coat 1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='paint_coat_2',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Paint Coat 2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='paint_coat_3',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Paint Coat 3'),
        ),
        migrations.AlterField(
            model_name='project',
            name='paint_coat_4',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Paint Coat 4'),
        ),
        migrations.AlterField(
            model_name='project',
            name='payment_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Payment 2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='payment_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Payment 3'),
        ),
        migrations.AlterField(
            model_name='project',
            name='payment_4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Payment 4'),
        ),
        migrations.AlterField(
            model_name='project',
            name='payment_5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Payment 5'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pqr_no',
            field=models.CharField(default='', max_length=50, verbose_name='PQR NO'),
        ),
        migrations.AlterField(
            model_name='project',
            name='preliminary_retention',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Preliminary Retention'),
        ),
        migrations.AlterField(
            model_name='project',
            name='standard_code',
            field=models.CharField(default='', max_length=50, verbose_name='Standard Code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='top_coat_ral_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Top Coat RAL Number'),
        ),
        migrations.AlterField(
            model_name='project',
            name='welding_wire_aws_class',
            field=models.CharField(default='', max_length=50, verbose_name='Welding Wire AWS Class'),
        ),
        migrations.AlterField(
            model_name='project',
            name='wps_no',
            field=models.CharField(default='', max_length=50, verbose_name='WPS NO'),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Length (mm)'),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='net_area_all',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Net Area (m²) for all'),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='net_area_single',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Net Area (m²) for one'),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='net_weight_all',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Net Weight (kg) for all'),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='revision_number',
            field=models.CharField(default='', max_length=20, verbose_name='Revision #'),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='single_part_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Single Part Weight'),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='sub_assembly_mark',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Sub-Assembly Mark'),
        ),
    ]
