# Generated by Django 5.1.4 on 2024-12-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_contract_amount_and_dp_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='number_of_structures',
        ),
    ]
