# Generated by Django 5.1.4 on 2024-12-31 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_shop_drawing_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='design_end_date',
        ),
        migrations.RemoveField(
            model_name='building',
            name='design_start_date',
        ),
        migrations.RemoveField(
            model_name='building',
            name='erection_applicable',
        ),
        migrations.RemoveField(
            model_name='building',
            name='erection_end_date',
        ),
        migrations.RemoveField(
            model_name='building',
            name='erection_start_date',
        ),
        migrations.RemoveField(
            model_name='building',
            name='production_end_date',
        ),
        migrations.RemoveField(
            model_name='building',
            name='production_start_date',
        ),
        migrations.RemoveField(
            model_name='building',
            name='shop_drawing_end_date',
        ),
        migrations.RemoveField(
            model_name='building',
            name='shop_drawing_start_date',
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_start_date', models.DateField(blank=True, null=True, verbose_name='Design Start Date')),
                ('design_end_date', models.DateField(blank=True, null=True, verbose_name='Design End Date')),
                ('shop_drawing_start_date', models.DateField(blank=True, null=True, verbose_name='Shop Drawing Start Date')),
                ('shop_drawing_end_date', models.DateField(blank=True, null=True, verbose_name='Shop Drawing End Date')),
                ('production_start_date', models.DateField(blank=True, null=True, verbose_name='Production Start Date')),
                ('production_end_date', models.DateField(blank=True, null=True, verbose_name='Production End Date')),
                ('erection_applicable', models.BooleanField(default=True, verbose_name='Erection Applicable')),
                ('erection_start_date', models.DateField(blank=True, null=True, verbose_name='Erection Start Date')),
                ('erection_end_date', models.DateField(blank=True, null=True, verbose_name='Erection End Date')),
                ('current_phase', models.CharField(blank=True, choices=[('DESIGN', 'Design Phase'), ('SHOP_DRAWING', 'Shop Drawing Phase'), ('PRODUCTION', 'Production Phase'), ('ERECTION', 'Erection Phase')], max_length=20, null=True, verbose_name='Current Phase')),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='core.building')),
            ],
            options={
                'verbose_name': 'Timeline',
                'verbose_name_plural': 'Timelines',
            },
        ),
    ]
