module.exports = {
  apps: [
    {
      name: 'hexa-steel-ots',
      script: 'node_modules/next/dist/bin/next',
      args: 'start',
      cwd: '/var/www/hexasteel.sa/ots',
      instances: 1,
      exec_mode: 'fork',
      node_args: '--max-old-space-size=1024 --expose-gc',
      watch: false,
      max_memory_restart: '800M',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        NEXT_PUBLIC_APP_URL: 'https://ots.hexasteel.sa',
      },
      cron_restart: '0 */6 * * *',
      error_file: '/var/www/hexasteel.sa/ots/logs/pm2-error.log',
      out_file: '/var/www/hexasteel.sa/ots/logs/pm2-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      kill_timeout: 10000,
      autorestart: true,
      max_restarts: 15,
      min_uptime: '30s',
      restart_delay: 4000,
      exp_backoff_restart_delay: 100,
    },
  ],
};
