# Generated by Django 5.1.4 on 2024-12-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_productionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='design_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Design Start Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='production_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Production Start Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='qc_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='QC Inspection Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='shop_drawing_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Shop Drawing Approval Date'),
        ),
    ]
