# Generated by Django 5.1.4 on 2024-12-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_timeline_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='design_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Design End Date'),
        ),
        migrations.AddField(
            model_name='building',
            name='design_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Design Start Date'),
        ),
        migrations.AddField(
            model_name='building',
            name='erection_applicable',
            field=models.BooleanField(default=True, verbose_name='Erection Applicable'),
        ),
        migrations.AddField(
            model_name='building',
            name='erection_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Erection End Date'),
        ),
        migrations.AddField(
            model_name='building',
            name='erection_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Erection Start Date'),
        ),
        migrations.AddField(
            model_name='building',
            name='production_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Production End Date'),
        ),
        migrations.AddField(
            model_name='building',
            name='production_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Production Start Date'),
        ),
        migrations.AddField(
            model_name='building',
            name='shop_drawing_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Shop Drawing End Date'),
        ),
        migrations.AddField(
            model_name='building',
            name='shop_drawing_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Shop Drawing Start Date'),
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
