'use client';

import Link from 'next/link';
import { FileText, Database, ExternalLink, Download, BookOpen } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

type FormEntry = {
  code: string;
  name: string;
  isoClause: string;
  procedure: string;
  href?: string;
  category: string;
};

type RecordEntry = {
  code: string;
  name: string;
  source: string;
  href?: string;
};

const FORMS: FormEntry[] = [
  { code: 'FRM-001', name: 'Document Change Request (DCR)', isoClause: 'ISO 9001 §7.5', procedure: 'ISP-001', href: '/ims/change-requests', category: 'Document Control' },
  { code: 'FRM-002', name: 'Supplier Evaluation & Approved Vendor List', isoClause: 'ISO 9001 §8.4', procedure: 'ISP-011', href: '/supply-chain/suppliers', category: 'Supply Chain' },
  { code: 'FRM-003', name: 'Training Needs Analysis', isoClause: 'ISO 9001 §7.2', procedure: 'ISP-006', href: '/hr/training', category: 'HR / Competence' },
  { code: 'FRM-004', name: 'Audit Schedule', isoClause: 'ISO 9001 §9.2', procedure: 'ISP-004', href: '/ims/audit-plans', category: 'Internal Audit' },
  { code: 'FRM-005', name: 'Internal Audit Report', isoClause: 'ISO 9001 §9.2', procedure: 'ISP-004', href: '/ims/audit-plans', category: 'Internal Audit' },
  { code: 'FRM-006', name: 'Audit Checklist', isoClause: 'ISO 9001 §9.2', procedure: 'ISP-004', href: '/ims/audit-plans', category: 'Internal Audit' },
  { code: 'FRM-024', name: 'OFI & Observation Register', isoClause: 'ISO 9001 §9.2, §10.3', procedure: 'ISP-004', href: '/ims/ofi-register', category: 'Internal Audit' },
  { code: 'FRM-025', name: 'Corrective Action & Verification Record', isoClause: 'ISO 9001 §10.2', procedure: 'ISP-005', href: '/ims/car', category: 'NCR / CAPA' },
  { code: 'FRM-026', name: 'Audit Checklist Library', isoClause: 'ISO 9001 §9.2', procedure: 'ISP-004', href: '/ims/checklist-library', category: 'Internal Audit' },
  { code: 'FRM-007', name: 'Non-Conformance Report (NCR + CAR)', isoClause: 'ISO 9001 §10.2', procedure: 'ISP-005', href: '/ims/audit-plans', category: 'NCR / CAPA' },
  { code: 'FRM-008', name: 'Management Review Record', isoClause: 'ISO 9001 §9.3', procedure: 'ISP-003', href: '/ims/management-review', category: 'Management Review' },
  { code: 'FRM-009', name: 'IMS Objectives & KPI Register', isoClause: 'ISO 9001 §6.2', procedure: 'ISP-030', href: '/business-planning/objectives', category: 'Planning' },
  { code: 'FRM-010', name: 'Personnel Competency & Training Record', isoClause: 'ISO 9001 §7.2', procedure: 'ISP-006', href: '/ims/competence-matrix', category: 'HR / Competence' },
  { code: 'FRM-011', name: 'Risk & Compliance Register', isoClause: 'ISO 9001 §6.1 / ISO 14001 §6.1 / ISO 45001 §6.1', procedure: 'ISP-002', href: '/ims/risks', category: 'Risk' },
  { code: 'FRM-012', name: 'Project Kickoff Checklist', isoClause: 'ISO 9001 §8.1', procedure: 'ISP-010', href: '/projects/kickoff', category: 'Projects' },
  { code: 'FRM-013', name: 'Welder Qualification Test Record (WQT)', isoClause: 'ISO 9001 §8.5.1', procedure: 'ISP-012', href: '/qc/welder-qualification', category: 'QC / Welding' },
  { code: 'FRM-014', name: 'Work / Welding Inspection Record (WIR)', isoClause: 'ISO 9001 §8.6', procedure: 'ISP-015', href: '/qc', category: 'QC / Welding' },
  { code: 'FRM-015', name: 'Inspection and Test Plan (ITP)', isoClause: 'ISO 9001 §8.6', procedure: 'ISP-015', href: '/qc', category: 'QC / Inspection' },
  { code: 'FRM-016', name: 'Material Inspection Receipt (MIR)', isoClause: 'ISO 9001 §8.4.3', procedure: 'ISP-011', href: '/supply-chain', category: 'Supply Chain' },
  { code: 'FRM-017', name: 'Dimensional Inspection Report', isoClause: 'ISO 9001 §8.6', procedure: 'ISP-015', href: '/qc', category: 'QC / Inspection' },
  { code: 'FRM-018', name: 'Coating Inspection Record (DFT)', isoClause: 'ISO 9001 §8.6', procedure: 'ISP-014', href: '/qc/coating', category: 'QC / Coating' },
  { code: 'FRM-019', name: 'Incident / Near-Miss Report', isoClause: 'ISO 45001 §10.2', procedure: 'ISP-020', href: '/ims/safety/incidents', category: 'HSE' },
  { code: 'FRM-020', name: 'Emergency Drill Record', isoClause: 'ISO 45001 §8.8', procedure: 'ISP-020', href: '/ims/safety/drills', category: 'HSE' },
  { code: 'FRM-021', name: 'Toolbox Talk Record', isoClause: 'ISO 45001 §7.3', procedure: 'ISP-020', href: '/ims/safety/toolbox-talks', category: 'HSE' },
  { code: 'FRM-022', name: 'Calibration Record / Certificate', isoClause: 'ISO 9001 §7.1.5', procedure: 'ISP-015', href: '/ims/calibration', category: 'QC / Equipment' },
];

const RECORDS: RecordEntry[] = [
  { code: 'REC-023', name: 'Project Card (PC)', source: 'Auto-generated by Project Setup Wizard', href: '/projects' },
  { code: 'REC-024', name: 'QMS Process List', source: 'Generated on demand from IMS Document Control', href: '/ims/processes' },
  { code: 'REC-025', name: 'Legal & Regulatory Register Export', source: 'Generated on demand — filtered view of FRM-011 (type=LEGAL)', href: '/ims/risks?type=LEGAL' },
];

const CATEGORIES = [
  'Document Control', 'Internal Audit', 'NCR / CAPA', 'Management Review',
  'Planning', 'Risk', 'HR / Competence', 'Supply Chain', 'Projects',
  'QC / Welding', 'QC / Inspection', 'QC / Coating', 'QC / Equipment', 'HSE',
];

const CATEGORY_COLORS: Record<string, string> = {
  'Document Control': 'bg-blue-100 text-blue-700 border-blue-200',
  'Internal Audit': 'bg-indigo-100 text-indigo-700 border-indigo-200',
  'NCR / CAPA': 'bg-red-100 text-red-700 border-red-200',
  'Management Review': 'bg-slate-100 text-slate-700 border-slate-200',
  'Planning': 'bg-purple-100 text-purple-700 border-purple-200',
  'Risk': 'bg-orange-100 text-orange-700 border-orange-200',
  'HR / Competence': 'bg-teal-100 text-teal-700 border-teal-200',
  'Supply Chain': 'bg-yellow-100 text-yellow-700 border-yellow-200',
  'Projects': 'bg-sky-100 text-sky-700 border-sky-200',
  'QC / Welding': 'bg-rose-100 text-rose-700 border-rose-200',
  'QC / Inspection': 'bg-pink-100 text-pink-700 border-pink-200',
  'QC / Coating': 'bg-amber-100 text-amber-700 border-amber-200',
  'QC / Equipment': 'bg-lime-100 text-lime-700 border-lime-200',
  'HSE': 'bg-green-100 text-green-700 border-green-200',
};

export function ImsFormsDirectoryClient() {
  return (
    <div className="p-6 space-y-8 max-w-screen-xl mx-auto">
      {/* Hero */}
      <div className="relative overflow-hidden rounded-xl p-6 text-white" style={{ background: 'linear-gradient(135deg, #2c3e50 0%, #34495e 60%, #2c3e50 100%)' }}>
        <div className="absolute inset-0 opacity-5" style={{ backgroundImage: 'repeating-linear-gradient(45deg, #fff 0, #fff 1px, transparent 0, transparent 50%)', backgroundSize: '20px 20px' }} />
        <div className="relative flex items-start gap-4">
          <div className="p-3 rounded-xl bg-white/10 backdrop-blur-sm">
            <FileText className="w-8 h-8 text-white" />
          </div>
          <div>
            <div className="flex items-center gap-2 mb-0.5">
              <h1 className="text-2xl font-bold tracking-tight">IMS Forms Directory</h1>
              <span className="text-xs bg-white/20 px-2 py-0.5 rounded-full">22 Forms + 3 Records</span>
            </div>
            <p className="text-slate-300 text-sm">Hexa-ISM-001 Rev.01 §12 — Controlled document and record registry</p>
            <p className="text-slate-400/70 text-xs font-mono mt-1">Procedure: Hexa-ISP-001 · ISO §7.5 · All forms are OTS™ data entry screens</p>
            <p className="text-slate-500/90 text-xs italic mt-1">All forms are OTS™ data entry screens. Records are system-generated outputs. No paper forms are maintained.</p>
          </div>
        </div>
      </div>

      {/* KPI strip */}
      <div className="grid grid-cols-3 gap-4">
        <div className="rounded-xl border p-4 bg-white">
          <p className="text-xs text-slate-500 font-medium">HEXA-FRM Forms</p>
          <p className="text-3xl font-bold text-[#2c3e50]">22</p>
          <p className="text-xs text-slate-400 mt-0.5">FRM-001 through FRM-022</p>
        </div>
        <div className="rounded-xl border p-4 bg-blue-50 border-blue-200">
          <p className="text-xs text-slate-500 font-medium">HEXA-REC Records</p>
          <p className="text-3xl font-bold text-blue-700">3</p>
          <p className="text-xs text-slate-400 mt-0.5">System-generated outputs</p>
        </div>
        <div className="rounded-xl border p-4 bg-emerald-50 border-emerald-200">
          <p className="text-xs text-slate-500 font-medium">ISM Revision</p>
          <p className="text-3xl font-bold text-emerald-700">Rev.01</p>
          <p className="text-xs text-slate-400 mt-0.5">Hexa-ISM-001 (2026-05-03)</p>
        </div>
      </div>

      {/* Form list by category */}
      {CATEGORIES.map(cat => {
        const catForms = FORMS.filter(f => f.category === cat);
        if (catForms.length === 0) return null;
        return (
          <div key={cat}>
            <div className="flex items-center gap-2 mb-3">
              <Badge variant="outline" className={`text-xs ${CATEGORY_COLORS[cat] ?? 'bg-gray-100 text-gray-700 border-gray-200'}`}>
                {cat}
              </Badge>
              <span className="text-xs text-slate-400">{catForms.length} form{catForms.length > 1 ? 's' : ''}</span>
            </div>
            <div className="rounded-lg border overflow-hidden">
              <table className="w-full text-sm">
                <thead className="bg-slate-50 border-b">
                  <tr>
                    <th className="px-4 py-2.5 text-left text-xs font-semibold text-slate-500 uppercase tracking-wide w-28">Form No.</th>
                    <th className="px-4 py-2.5 text-left text-xs font-semibold text-slate-500 uppercase tracking-wide">Form Name</th>
                    <th className="px-4 py-2.5 text-left text-xs font-semibold text-slate-500 uppercase tracking-wide hidden md:table-cell">ISO Clause</th>
                    <th className="px-4 py-2.5 text-left text-xs font-semibold text-slate-500 uppercase tracking-wide hidden lg:table-cell">Procedure</th>
                    <th className="px-4 py-2.5 text-right text-xs font-semibold text-slate-500 uppercase tracking-wide w-24">Open</th>
                  </tr>
                </thead>
                <tbody className="divide-y">
                  {catForms.map(form => (
                    <tr key={form.code} className="hover:bg-slate-50/50 transition-colors">
                      <td className="px-4 py-3">
                        <span className="font-mono text-xs font-bold text-[#2c3e50] bg-slate-100 px-2 py-0.5 rounded">
                          HEXA-{form.code}
                        </span>
                      </td>
                      <td className="px-4 py-3 font-medium text-slate-800">{form.name}</td>
                      <td className="px-4 py-3 text-xs text-slate-500 font-mono hidden md:table-cell">{form.isoClause}</td>
                      <td className="px-4 py-3 text-xs text-slate-500 font-mono hidden lg:table-cell">Hexa-{form.procedure}</td>
                      <td className="px-4 py-3 text-right">
                        {form.href ? (
                          <Link href={form.href}>
                            <Button size="sm" variant="outline" className="h-7 text-xs gap-1">
                              Open <ExternalLink className="w-3 h-3" />
                            </Button>
                          </Link>
                        ) : (
                          <span className="text-xs text-slate-400">—</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        );
      })}

      {/* System-Generated Records Section */}
      <Card className="border-dashed border-2 border-blue-200">
        <CardHeader className="pb-3">
          <CardTitle className="text-base font-semibold flex items-center gap-2 text-blue-700">
            <Database className="w-5 h-5" />
            System-Generated Records (HEXA-REC)
            <Badge className="bg-blue-100 text-blue-700 border-blue-200 text-xs ml-1">No data entry</Badge>
          </CardTitle>
          <p className="text-xs text-slate-500 -mt-1">
            These are not data-entry forms. They are automatically generated outputs from OTS system data.
            Use the &quot;Generate&quot; button to produce the record on demand.
          </p>
        </CardHeader>
        <CardContent className="pt-0">
          <div className="rounded-lg border overflow-hidden">
            <table className="w-full text-sm">
              <thead className="bg-blue-50 border-b">
                <tr>
                  <th className="px-4 py-2.5 text-left text-xs font-semibold text-blue-600 uppercase tracking-wide w-28">Record No.</th>
                  <th className="px-4 py-2.5 text-left text-xs font-semibold text-blue-600 uppercase tracking-wide">Record Name</th>
                  <th className="px-4 py-2.5 text-left text-xs font-semibold text-blue-600 uppercase tracking-wide hidden md:table-cell">Source</th>
                  <th className="px-4 py-2.5 text-right text-xs font-semibold text-blue-600 uppercase tracking-wide w-28">Generate</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                {RECORDS.map(rec => (
                  <tr key={rec.code} className="hover:bg-blue-50/30 transition-colors">
                    <td className="px-4 py-3">
                      <span className="font-mono text-xs font-bold text-blue-700 bg-blue-100 px-2 py-0.5 rounded">
                        HEXA-{rec.code}
                      </span>
                    </td>
                    <td className="px-4 py-3 font-medium text-slate-800">{rec.name}</td>
                    <td className="px-4 py-3 text-xs text-slate-500 hidden md:table-cell">{rec.source}</td>
                    <td className="px-4 py-3 text-right">
                      {rec.href ? (
                        <Link href={rec.href}>
                          <Button size="sm" variant="outline" className="h-7 text-xs gap-1 border-blue-300 text-blue-700 hover:bg-blue-50">
                            <Download className="w-3 h-3" /> Generate
                          </Button>
                        </Link>
                      ) : (
                        <span className="text-xs text-slate-400">Auto</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>

      {/* Footer note */}
      <div className="flex items-start gap-3 bg-slate-50 border rounded-lg p-4">
        <BookOpen className="w-4 h-4 text-slate-400 mt-0.5 shrink-0" />
        <div className="text-xs text-slate-500 space-y-1">
          <p className="font-semibold text-slate-600">Forms Registry — Hexa-ISM-001 Rev.01 §12</p>
          <p>This directory supersedes the legacy 27-form registry. Forms FRM-001 to FRM-022 are active. Legacy forms FRM-023 through FRM-027 have been merged into FRM-011 (Risk & Compliance Register) and are no longer standalone forms. FRM-002 and FRM-004 are now HEXA-REC-024 (system-generated).</p>
        </div>
      </div>
    </div>
  );
}
