-- Add TASK_COMPLETED to NotificationType enum
ALTER TABLE `notifications` MODIFY COLUMN `type` ENUM('TASK_ASSIGNED', 'TASK_COMPLETED', 'APPROVAL_REQUIRED', 'DEADLINE_WARNING', 'APPROVED', 'REJECTED', 'SYSTEM') NOT NULL;
