INSERT IGNORE INTO fin_chart_of_accounts (account_code, account_name, account_name_ar, account_type, account_category, parent_code, display_order) VALUES
  ('1', 'ASSETS', 'Assets', 'asset', 'Other Assets', NULL, 10),
  ('11', 'Non-Current assets', 'Non-Current assets', 'asset', 'Fixed Assets', NULL, 20),
  ('110', 'Fixed assets', 'الأصول الثابتة', 'asset', 'Fixed Assets', NULL, 30),
  ('11001', 'Cars', 'سيارات', 'asset', 'Fixed Assets', NULL, 40),
  ('1100101', 'Assets - Vehicles', 'أصول - سيارات', 'asset', 'Fixed Assets', NULL, 50),
  ('11002', 'Furniture', 'أثاث ومفروشات', 'asset', 'Fixed Assets', NULL, 60),
  ('11003', 'Machinery and equipment', 'آلات ومعدات', 'asset', 'Fixed Assets', NULL, 70),
  ('1100301', 'Cranes', 'الكرينات', 'asset', 'Fixed Assets', NULL, 80),
  ('1100302', 'Purchasing Forklift', 'شراء فوركلفت', 'asset', 'Fixed Assets', NULL, 90),
  ('1100303', 'Iron ٍSaw-منشار حديد', 'Iron ٍSaw-منشار حديد', 'asset', 'Fixed Assets', NULL, 100),
  ('1100304', 'مكائن اللحام', 'مكائن اللحام', 'asset', 'Fixed Assets', NULL, 110),
  ('11004', 'Computers, software, printers and telephones', 'أجهزة كمبيوتر وبرامج وطابعات وتليفونات', 'asset', 'Fixed Assets', NULL, 120),
  ('11004001', 'Odoo', 'برنامج Odoo', 'asset', 'Fixed Assets', NULL, 130),
  ('11005', 'Electrical devices', 'أجهزة كهربائية', 'asset', 'Fixed Assets', NULL, 140),
  ('11006', 'Advertisement boards', 'لوحات اعلانية', 'asset', 'Fixed Assets', NULL, 150),
  ('11007', 'tools', 'العدد والأدوات', 'asset', 'Fixed Assets', NULL, 160),
  ('111', 'Fixed asset', 'Property, Plant, & Equipment', 'asset', 'Fixed Assets', NULL, 170),
  ('111001', 'Furniture', 'Furniture and Fixtures أثاث و مفروشات', 'asset', 'Fixed Assets', NULL, 180),
  ('111002', 'Tools', 'Tools عدد و أدوات', 'asset', 'Fixed Assets', NULL, 190),
  ('111003', 'Devices', 'Electrical& Devices أجهزة كهربائية', 'asset', 'Fixed Assets', NULL, 200),
  ('12', 'Current assets', 'Current assets اصول متداولة', 'asset', 'Current Assets', NULL, 210),
  ('120', 'Current assets', 'الاصول المتداولة', 'asset', 'Current Assets', NULL, 220),
  ('12001', 'Cash', 'النقدية', 'asset', 'Bank & Cash', NULL, 230),
  ('1200101', 'Primary Fund', 'الصندوق الرئيسي', 'asset', 'Bank & Cash', NULL, 240),
  ('12002', 'Banks', 'البنوك', 'asset', 'Current Assets', NULL, 250),
  ('1200201', 'Alinma bank', 'بنك الانماء', 'asset', 'Bank & Cash', NULL, 260),
  ('1200201001', 'Al Inma Bank S.R 68202607969000', 'بنك الانماء بالريال 68202607969000', 'asset', 'Bank & Cash', NULL, 270),
  ('1200201002', 'Al Inma Bank USD 84 0026 0796 9001', 'بنك الانماء دولار 84 0026 0796 9001', 'asset', 'Bank & Cash', NULL, 280),
  ('1200201003', 'Hexa Steel -Al Inma Bank S.R 68205995362000', 'Hexa Steel -بنك الانماء بالريال68205995362000', 'asset', 'Bank & Cash', NULL, 290),
  ('1200201004', 'Hexa Steel -Al Inma Bank USD 84 0059 9536 2001', 'Hexa Steel -بنك الانماءUSD 84 0059 9536 2001', 'asset', 'Bank & Cash', NULL, 300),
  ('1200202', 'ٍRiyad Bank', 'بنك الرياض', 'asset', 'Bank & Cash', NULL, 310),
  ('1200202001', 'SA2920000002000239019940 - Riyad Bank SAR', 'بنك الرياض بالريال2000239019940', 'asset', 'Bank & Cash', NULL, 320),
  ('1200202002', 'SA6120000002000239010440 - Riyad Bank USD', 'بنك الرياض بالدولار 2000239010440', 'asset', 'Bank & Cash', NULL, 330),
  ('1200203', 'Sty Pay Bank', 'بنكSTCPAY', 'asset', 'Bank & Cash', NULL, 340),
  ('1200203001', 'Stc Bank SA483010094000136115683', 'Stc Bank SA483010094000136115683', 'asset', 'Bank & Cash', NULL, 350),
  ('1200204', 'Bank Albilad', 'بنك البلاد | Bank Albilad', 'asset', 'Bank & Cash', NULL, 360),
  ('1200204001', 'Bank Albilad 422137969980008 SAR -Hexa', 'بنك البلاد ح/ 422137969980008 ريال -اتحاد', 'asset', 'Bank & Cash', NULL, 370),
  ('12003', 'Customers', 'العملاء', 'asset', 'Accounts Receivable', NULL, 380),
  ('12003001', 'Receivables - Local Customers', 'ذمم عملاء محليون', 'asset', 'Accounts Receivable', NULL, 390),
  ('12004', 'Covenant', 'العهد', 'asset', 'Current Assets', NULL, 400),
  ('1200401', 'Temporary ٌReign', 'عهد مؤقتة', 'asset', 'Current Assets', NULL, 410),
  ('12005', 'Loans', 'السلف', 'asset', 'Current Assets', NULL, 420),
  ('12006', 'Upfront expenses', 'المصاريف المقدمة', 'asset', 'Current Assets', NULL, 430),
  ('12007', 'مدينون متنوعون', 'مدينون متنوعون', 'asset', 'Current Assets', NULL, 440),
  ('12008', 'ضمانات ابتدائية', 'ضمانات ابتدائية', 'asset', 'Current Assets', NULL, 450),
  ('12009', 'ضمانات نهائية', 'ضمانات نهائية', 'asset', 'Current Assets', NULL, 460),
  ('12009001', 'Advance Payment Guarantee Letters', 'خطابات ضمان دفعة مقدمة', 'asset', 'Current Assets', NULL, 470),
  ('12010', 'اوراق قبض', 'اوراق قبض', 'asset', 'Inventory', NULL, 480),
  ('12012', 'Inventory', 'المخزون', 'asset', 'Inventory', NULL, 490),
  ('1201201', 'Raw Materials Inventory', 'مخزون المواد الخام', 'asset', 'Inventory', NULL, 500);

INSERT IGNORE INTO fin_chart_of_accounts (account_code, account_name, account_name_ar, account_type, account_category, parent_code, display_order) VALUES
  ('1201202', 'Work-in-Progress Inventory', 'مخزون تحت الانتاج', 'asset', 'Inventory', NULL, 510),
  ('1201203', 'Spare Parts Inventory', 'مخزون قطع الغيار', 'asset', 'Inventory', NULL, 520),
  ('121', 'Cash And Bank', 'Cash And Bank النقد و ما في حكمها', 'asset', 'Bank & Cash', NULL, 530),
  ('1211', 'Cash Book', 'Cash Book صناديق النقدية', 'asset', 'Bank & Cash', NULL, 540),
  ('121101', 'Cash Book', 'Cash صندوق النقدية الرئيسي', 'asset', 'Bank & Cash', NULL, 550),
  ('1212', 'bank', 'banks البنوك', 'asset', 'Bank & Cash', NULL, 560),
  ('121201', 'Alinma bank SAR مصرف الإنماء', 'Alinma bank SAR مصرف الإنماء', 'asset', 'Bank & Cash', NULL, 570),
  ('121202', 'Alinma bank USD مصرف الإنماء', 'Alinma bank USD مصرف الإنماء', 'asset', 'Bank & Cash', NULL, 580),
  ('122', 'Inventories', 'Inventories المخزون', 'asset', 'Inventory', NULL, 590),
  ('1221', 'Inventory', 'Inventory Raw Materials', 'asset', 'Inventory', NULL, 600),
  ('1222', 'Inventory', 'Inventory Work in Process', 'asset', 'Inventory', NULL, 610),
  ('1223', 'Inventory', 'Inventory Of Finished Goods', 'asset', 'Inventory', NULL, 620),
  ('122301', 'Inventory', 'Inventory Hardware', 'asset', 'Inventory', NULL, 630),
  ('123', 'AR', 'Account Receivables ذمم مدينة تجارية', 'asset', 'Accounts Receivable', NULL, 640),
  ('1231', 'Local Customers', 'Local Customers', 'asset', 'Accounts Receivable', NULL, 650),
  ('1232', 'International Customers', 'International Customers', 'asset', 'Accounts Receivable', NULL, 660),
  ('124', 'Petty Cash', 'Petty Cash عهد موظفين', 'asset', 'Current Assets', NULL, 670),
  ('124001', 'Petty Cash', 'Petty Cash Eng. Walid Dami', 'asset', 'Current Assets', NULL, 680),
  ('125', 'Other Debiter', 'Other Debit Balance أرصدة مدينة أخرى', 'asset', 'Current Assets', NULL, 690),
  ('125001', 'Advance payments', 'Advance payments to suppliers دفعات مقدمه للموردين', 'asset', 'Current Assets', NULL, 700),
  ('127', 'Prepaid to Short-term projects no#', 'Prepaid to Short-term projects no#', 'asset', 'Current Assets', NULL, 710),
  ('128', 'Input VAT', 'Input VAT ضريبة المدخلات', 'asset', 'VAT Input', NULL, 720),
  ('1280', 'VAT Purchases', 'ضريبة القيمة المضافة مشتريات', 'asset', 'VAT Input', NULL, 730),
  ('128001', 'Purchases Tax', 'Input VAT ( Purchases Tax) ضريبة المدخلات', 'asset', 'VAT Input', NULL, 740),
  ('128002', 'VAT Purchases 5%', 'ضريبة القيمة المضافة مشتريات 5%', 'asset', 'VAT Input', NULL, 750),
  ('2', 'Liabilities', 'Liabilities الالتزامات', 'liability', 'Current Liabilities', NULL, 760),
  ('21', 'Non-Current Liabilities', 'Non-Current Liabilities المطلوبات الغير متداولة', 'liability', 'Current Liabilities', NULL, 770),
  ('210', 'خصوم قصيرة الاجل', 'خصوم قصيرة الاجل', 'liability', 'Current Liabilities', NULL, 780),
  ('2101', 'Advance revenue', 'الايرادات المقدمة', 'liability', 'Current Liabilities', NULL, 790),
  ('2102', 'VAT Sales', 'ضريبة القيمة المضافة مبيعات', 'liability', 'VAT Payable', NULL, 800),
  ('210201', 'VAT Sales 15%', 'ضريبة القيمة المضافة مبيعات 15%', 'liability', 'VAT Payable', NULL, 810),
  ('210202', 'VAT Sales 5%', 'ضريبة القيمة المضافة مبيعات 5%', 'liability', 'VAT Payable', NULL, 820),
  ('2103', 'المصاريف المستحقة', 'المصاريف المستحقة', 'liability', 'Current Liabilities', NULL, 830),
  ('2104', 'Contractors & Suppliers', 'ذمم مورديين', 'liability', 'Accounts Payable', NULL, 840),
  ('210401', 'Accounts Payable -local Suppliers Materials', 'ذمم موردين محليون مواد', 'liability', 'Accounts Payable', NULL, 850),
  ('210402', 'Accounts Payable - local Suppliers Consumables', 'ذمم موردين محليون مستهلكات', 'liability', 'Accounts Payable', NULL, 860),
  ('210403', 'Accounts Payable -Service Suppliers', 'ذمم موردين خدمات', 'liability', 'Accounts Payable', NULL, 870),
  ('210404', 'Accounts Payable - Subcontractors', 'ذمم مقاولي الباطن', 'liability', 'Accounts Payable', NULL, 880),
  ('210405', 'Accounts Payable - External Suppliers Materials', 'ذمم موردين خارجيون مواد', 'liability', 'Accounts Payable', NULL, 890),
  ('2105', 'Third Parties', 'أطراف ثالثة', 'liability', 'Current Liabilities', NULL, 900),
  ('2106', 'استحقاق العاملين', 'استحقاق العاملين', 'liability', 'Current Liabilities', NULL, 910),
  ('2107', 'دائنون متنوعون', 'دائنون متنوعون', 'liability', 'Current Liabilities', NULL, 920),
  ('2108', 'مجمع مخصص اهلاك الاصول', 'مجمع مخصص اهلاك الاصول', 'liability', 'Current Liabilities', NULL, 930),
  ('2108001', 'Accumulated Depreciation- Cars', 'مجمع استهلاك السيارات', 'liability', 'Current Liabilities', NULL, 940),
  ('2108002', 'Accumulated Depreciation- Furniture', 'مجمع استهلاك الاثاث والمفروشات', 'liability', 'Current Liabilities', NULL, 950),
  ('2108003', 'Accumulated Depreciation- Machinery & equipment', 'مجمع استهلاك الآلات والمعدات', 'liability', 'Current Liabilities', NULL, 960),
  ('2108004', 'Accumulated Depreciation- Electrical & Office Equipment', 'مجمع استهلاك اجهزة كهربائية ومكتبية', 'liability', 'Current Liabilities', NULL, 970),
  ('2108005', 'Accumulated Depreciation-Tools', 'مجمع استهلاك العدد والادوات', 'liability', 'Current Liabilities', NULL, 980),
  ('2109', 'Paying VAT', 'تسوية حساب ضريبة القيمة المضافة', 'liability', 'VAT Payable', NULL, 990),
  ('22', 'Current Liabilities', 'Current Liabilities المطلوبات المتداولة', 'liability', 'Current Liabilities', NULL, 1000);

INSERT IGNORE INTO fin_chart_of_accounts (account_code, account_name, account_name_ar, account_type, account_category, parent_code, display_order) VALUES
  ('220', 'خصوم طويلة الأجل', 'خصوم طويلة الأجل', 'liability', 'Non-Current Liabilities', NULL, 1010),
  ('2201', 'قروض', 'قروض', 'liability', 'Non-Current Liabilities', NULL, 1020),
  ('2202', 'تمويل من أطراف ذات علاقة', 'تمويل من أطراف ذات علاقة', 'liability', 'Non-Current Liabilities', NULL, 1030),
  ('2211', 'Local Vendors', 'Local Vendors موردين محليين', 'liability', 'Accounts Payable', NULL, 1040),
  ('2212', 'International Vendors', 'International Vendors الموردين الدوليين', 'liability', 'Accounts Payable', NULL, 1050),
  ('223', 'Employee Benefits', 'Employee Benefits استحقاقات الموظفين', 'liability', 'Current Liabilities', NULL, 1060),
  ('224', 'Accrued Expenses', 'Accrued Expenses المصاريف المستحقة', 'liability', 'Current Liabilities', NULL, 1070),
  ('224001', 'Accured VAT', 'Accured VAT', 'liability', 'VAT Payable', NULL, 1080),
  ('224002', 'Accured Zakat Exp.', 'Accured Zakat Exp.', 'liability', 'Current Liabilities', NULL, 1090),
  ('225', 'Other Crediter', 'Other Credit Balance ذمم دائنة  أخرى', 'liability', 'Current Liabilities', NULL, 1100),
  ('225001', 'Unearned Revenue', 'Unearned Revenue إيرادات مقدمة', 'liability', 'Current Liabilities', NULL, 1110),
  ('226', 'Output VAT', 'Output VAT ضريبة المخرجات', 'liability', 'VAT Payable', NULL, 1120),
  ('226001', 'Sales Tax', 'Output VAT (Sales Tax) ضريبة المخرجات', 'liability', 'VAT Payable', NULL, 1130),
  ('3', 'Equity', 'Owners Equity حقوق الملكية', 'equity', 'Equity', NULL, 1140),
  ('31', 'Capital Account', 'Capital Account', 'equity', 'Share Capital', NULL, 1150),
  ('310', 'رأس المال', 'رأس المال', 'equity', 'Share Capital', NULL, 1160),
  ('310001', 'Capital Account - Partner 1 رأس المال', 'Capital Account - Partner 1 رأس المال', 'equity', 'Share Capital', NULL, 1170),
  ('310002', 'Legal Reserve رأس مال احتياطي نظامي', 'Legal Reserve رأس مال احتياطي نظامي', 'equity', 'Share Capital', NULL, 1180),
  ('32', 'Partners Current Acc', 'Partners Current Account الحساب الجاري للشركاء', 'equity', 'Partners Current Account', NULL, 1190),
  ('320', 'جاري الشركاء', 'جاري الشركاء', 'equity', 'Partners Current Account', NULL, 1200),
  ('320001', 'Partner Current  Account جاري شريك', 'Partner Current  Account جاري شريك', 'equity', 'Partners Current Account', NULL, 1210),
  ('32001', 'Owners Equity', 'جاري صاحب الشركة', 'equity', 'Partners Current Account', NULL, 1220),
  ('33', 'P&L', 'Profit And Loss الارباح/الخسائر المبقاه', 'equity', 'Retained Earnings', NULL, 1230),
  ('330', 'ارباح وخسائر مرحلة', 'ارباح وخسائر مرحلة', 'equity', 'Retained Earnings', NULL, 1240),
  ('330001', 'Profit And Loss 2020 الارباح المبقاه', 'Profit And Loss 2020 الارباح المبقاه', 'equity', 'Retained Earnings', NULL, 1250),
  ('340', 'أرباح وخسائر مبقاة', 'أرباح وخسائر مبقاة', 'equity', 'Retained Earnings', NULL, 1260),
  ('4', 'EX', 'Expenses', 'expense', 'Operating Expenses', NULL, 1270),
  ('400000', 'expenses', 'المصاريف', 'expense', 'Operating Expenses', NULL, 1280),
  ('41', 'Direct Expenses', 'Direct Expenses', 'expense', 'General & Administrative', NULL, 1290),
  ('410000', 'General and administrative expenses', 'مصاريف عمومية وإدارية', 'expense', 'General & Administrative', NULL, 1300),
  ('410001', 'COGS', 'Cost Of Food Sold', 'expense', 'General & Administrative', NULL, 1310),
  ('410100', 'rents', 'ايجارات', 'expense', 'General & Administrative', NULL, 1320),
  ('410101', 'Head office rent', 'ايجار المقر الرئيسي', 'expense', 'General & Administrative', NULL, 1330),
  ('410102', 'Workers\' accommodation for rent', 'ايجار سكن العمال', 'expense', 'General & Administrative', NULL, 1340),
  ('410200', 'Salaries and wages', 'رواتب وأجور', 'expense', 'General & Administrative', NULL, 1350),
  ('410300', 'allowances', 'البدلات', 'expense', 'General & Administrative', NULL, 1360),
  ('410301', 'housing allowance', 'بدل السكن', 'expense', 'General & Administrative', NULL, 1370),
  ('410302', 'relocation allowance', 'بدل الانتقال', 'expense', 'General & Administrative', NULL, 1380),
  ('410303', 'Annual leave allowance', 'بدل اجازة سنوية', 'expense', 'General & Administrative', NULL, 1390),
  ('410304', 'Travel ticket allowance', 'بدل تذاكر السفر', 'expense', 'General & Administrative', NULL, 1400),
  ('410305', 'Other allowances', 'بدلات اخري', 'expense', 'General & Administrative', NULL, 1410),
  ('410400', 'Stationery and stationery', 'قرطاسية وادوات مكتبية', 'expense', 'General & Administrative', NULL, 1420),
  ('410500', 'Phone and internet', 'هاتف وانترنت', 'expense', 'General & Administrative', NULL, 1430),
  ('410600', 'Hospitality expenses', 'مصاريف ضيافة', 'expense', 'General & Administrative', NULL, 1440),
  ('410700', 'Governmental expenses', 'مصاريف حكومية', 'expense', 'General & Administrative', NULL, 1450),
  ('410701', 'Governmental expenses for issuance, renewal, exit and return', 'مصاريف حكومية اصدار وتجديد وخروج وعودة', 'expense', 'General & Administrative', NULL, 1460),
  ('410702', 'Governmental expenses, the General Authority for Zakat and Income', 'مصاريف حكومية الهيئة العامة للزكاة والدخل', 'expense', 'General & Administrative', NULL, 1470),
  ('410703', 'Government expenses social insurance', 'مصاريف حكومية التأمينات الاجتماعية', 'expense', 'General & Administrative', NULL, 1480),
  ('410704', 'Miscellaneous government expenses', 'مصاريف حكومية متنوعة', 'expense', 'General & Administrative', NULL, 1490),
  ('410800', 'Water and electricity expenses', 'مصاريف مياة وكهرباء', 'expense', 'General & Administrative', NULL, 1500);

INSERT IGNORE INTO fin_chart_of_accounts (account_code, account_name, account_name_ar, account_type, account_category, parent_code, display_order) VALUES
  ('410900', 'Advertising expenses', 'مصاريف دعاية واعلان', 'expense', 'General & Administrative', NULL, 1510),
  ('411000', 'Bank fee charges', 'مصاريف رسوم بنكية', 'expense', 'General & Administrative', NULL, 1520),
  ('411100', 'Various general and administrative expenses', 'مصاريف ادارية وعمومية متنوعة', 'expense', 'General & Administrative', NULL, 1530),
  ('411200', 'medical insurance', 'تأمين طبي', 'expense', 'General & Administrative', NULL, 1540),
  ('411300', 'Gasoline expenses', 'مصاريف بنزين', 'expense', 'General & Administrative', NULL, 1550),
  ('411400', 'hospital bill', 'مصاريف علاج', 'expense', 'General & Administrative', NULL, 1560),
  ('411500', 'Bonuses for employees', 'مكافأت للموظفين', 'expense', 'General & Administrative', NULL, 1570),
  ('411600', 'Discount permitted', 'خصم مسموح به', 'expense', 'General & Administrative', NULL, 1580),
  ('411700', 'Audit and legal audit expenses', 'مصاريف تدقيق حسابات ومراجعة قانونية', 'expense', 'General & Administrative', NULL, 1590),
  ('411800', 'End of service expenses for employees', 'مصاريف نهاية خدمة للموظفين', 'expense', 'General & Administrative', NULL, 1600),
  ('411900', 'Fixed asset depreciation expenses', 'مصروفات أهلاك الاصول الثابتة', 'expense', 'General & Administrative', NULL, 1610),
  ('4119001', 'Depreciation -Cars', 'مصاريف استهلاك السيارات', 'expense', 'General & Administrative', NULL, 1620),
  ('42', 'Indirect Expenses', 'Indirect Expenses', 'expense', 'Operating Expenses', NULL, 1630),
  ('420000', 'Operating expenses - projects', 'مصاريف تشغيلية - المشاريع', 'expense', 'Cost of Sales', NULL, 1640),
  ('420100', 'Operational - Cost of Goods Sold COGS', 'تشغيلية - تكلفة البضاعة المباعة COGS', 'expense', 'Cost of Sales', NULL, 1650),
  ('420101', 'Iron ore materials', 'مواد خام الحديد', 'expense', 'Cost of Sales', NULL, 1660),
  ('420102', 'Other raw materials', 'مواد خام أخرى', 'expense', 'Cost of Sales', NULL, 1670),
  ('420103', 'screws', 'براغي', 'expense', 'Cost of Sales', NULL, 1680),
  ('420104', 'manufacturing materials', 'مواد تصنيع', 'expense', 'Cost of Sales', NULL, 1690),
  ('420105', 'paint', 'الدهان', 'expense', 'Cost of Sales', NULL, 1700),
  ('420200', 'Operational / subcontractors', 'تشغيلية / مقاولي الباطن', 'expense', 'Cost of Sales', NULL, 1710),
  ('420300', 'operational/manufacturing services', 'تشغيلية / خدمات تصنيع', 'expense', 'Cost of Sales', NULL, 1720),
  ('420301', 'Galvanization', 'الجلفنة', 'expense', 'Cost of Sales', NULL, 1730),
  ('420302', 'Paints out of the factory', 'دهانات خارج المصنع', 'expense', 'Cost of Sales', NULL, 1740),
  ('420303', 'Manufacture outside the factory', 'تصنيع خارج المصنع', 'expense', 'Cost of Sales', NULL, 1750),
  ('420304', 'External labor rental', 'إيجار عمالة خارجية', 'expense', 'Cost of Sales', NULL, 1760),
  ('420400', 'Design services', 'خدمات تصميم', 'expense', 'Cost of Sales', NULL, 1770),
  ('420500', 'Operational / equipment rental', 'تشغيلية / إيجار معدات', 'expense', 'Cost of Sales', NULL, 1780),
  ('420600', 'Operational / transportation work', 'تشغيلية / اعمال نقل', 'expense', 'Cost of Sales', NULL, 1790),
  ('420700', 'operational / food', 'تشغيلية / طعام', 'expense', 'Cost of Sales', NULL, 1800),
  ('420800', 'Operational / telephone and internet', 'تشغيلية / هاتف وانترنت', 'expense', 'Cost of Sales', NULL, 1810),
  ('420900', 'operational / electrical materials', 'تشغيلية / مواد كهرباء', 'expense', 'Cost of Sales', NULL, 1820),
  ('421000', 'operational / petrol', 'تشغيلية / بنزين', 'expense', 'Operating Expenses', NULL, 1830),
  ('421100', 'Operational / rentals', 'تشغيلية / ايجارات', 'expense', 'Operating Expenses', NULL, 1840),
  ('421200', 'Operational / Welding Materials', 'تشغيلية / مواد مكن اللحام', 'expense', 'Operating Expenses', NULL, 1850),
  ('421300', 'Operational/equipment maintenance', 'تشغيلية / اعمال صيانة معدات', 'expense', 'Operating Expenses', NULL, 1860),
  ('421400', 'Operational / electricity and water', 'تشغيلية / كهرباء ومياة', 'expense', 'Operating Expenses', NULL, 1870),
  ('421500', 'Operational / Miscellaneous Expenses', 'تشغيلية / مصروفات متنوعة', 'expense', 'Operating Expenses', NULL, 1880),
  ('421600', 'Operational / depreciation of fixed assets', 'تشغيلية / اهلاك الأصول الثابتة', 'expense', 'Operating Expenses', NULL, 1890),
  ('5', 'RV', 'Revenues', 'revenue', 'Sales Revenue', NULL, 1900),
  ('500001', 'Revenue-Contracting', 'Revenue-Contracting ايرادات المقاولات', 'revenue', 'Sales Revenue', NULL, 1910),
  ('500002', 'Revenue-Trading', 'Revenue-Trading ايرادات التجارة', 'revenue', 'Sales Revenue', NULL, 1920),
  ('500003', 'Other Revenues', 'Other Revenues ايرادات اخرى', 'revenue', 'Other Income', NULL, 1930),
  ('510', 'Operating Revenues', 'إيرادات تشغيلية', 'revenue', 'Operating Revenue', NULL, 1940),
  ('5101', 'Operating contract revenue', 'ايراداات عقود التشغيل', 'revenue', 'Operating Revenue', NULL, 1950),
  ('520', 'Other Revenues', 'إيرادات  اخري', 'revenue', 'Other Income', NULL, 1960),
  ('530', 'Sales Revenue', 'إيرادات المبيعات', 'revenue', 'Sales Revenue', NULL, 1970),
  ('53001', 'Products Sales Revenue', 'إيرادات مبيعات المنتجات', 'revenue', 'Sales Revenue', NULL, 1980),
  ('5300101', 'Products Sales Revenue - Trading', 'إيرادات مبيعات المنتجات - تجارة', 'revenue', 'Sales Revenue', NULL, 1990),
  ('53002', 'Services Sales Revenue', 'إيرادات مبيعات الخدمات', 'revenue', 'Sales Revenue', NULL, 2000);

INSERT IGNORE INTO fin_chart_of_accounts (account_code, account_name, account_name_ar, account_type, account_category, parent_code, display_order) VALUES
  ('5300201', 'Fabrication Service without Material', 'خدمة تصنيع حديد بدون مواد', 'revenue', 'Sales Revenue', NULL, 2010),
  ('5300202', 'Services Sales Revenue - Laser Cutting', 'إيرادات مبيعات الخدمات - قص ليزر', 'revenue', 'Sales Revenue', NULL, 2020),
  ('53003', 'Other Income', 'ايرادات اخري', 'revenue', 'Sales Revenue', NULL, 2030),
  ('53003001', 'Income From The Sale Of Fixed Assets', 'ايراد بيع الاصول الثابتة', 'revenue', 'Sales Revenue', NULL, 2040);

