/**
 * Clear Operations Control Seeded Data
 * 
 * This script removes all seeded test data from Operations Control tables:
 * - RiskEvents
 * - WorkUnitDependencies  
 * - WorkUnits (only orphaned ones with non-existent references)
 * - ResourceCapacity (seeded resources)
 * 
 * Run with: npx ts-node scripts/clear-operations-seed-data.ts
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🧹 Clearing Operations Control seeded data...\n');

  // 1. Clear all RiskEvents (they will be regenerated by the engine)
  const deletedRisks = await prisma.riskEvent.deleteMany({});
  console.log(`✓ Deleted ${deletedRisks.count} RiskEvents`);

  // 2. Clear all WorkUnitDependencies
  const deletedDeps = await prisma.workUnitDependency.deleteMany({});
  console.log(`✓ Deleted ${deletedDeps.count} WorkUnitDependencies`);

  // 3. Find and delete orphaned WorkUnits (those with non-existent references)
  const allWorkUnits = await prisma.workUnit.findMany({
    select: { id: true, referenceModule: true, referenceId: true },
  });

  let orphanedCount = 0;
  for (const wu of allWorkUnits) {
    let exists = false;
    try {
      switch (wu.referenceModule) {
        case 'Task':
          exists = !!(await prisma.task.findUnique({ where: { id: wu.referenceId }, select: { id: true } }));
          break;
        case 'WorkOrder':
          exists = !!(await prisma.workOrder.findUnique({ where: { id: wu.referenceId }, select: { id: true } }));
          break;
        case 'RFIRequest':
          exists = !!(await prisma.rFIRequest.findUnique({ where: { id: wu.referenceId }, select: { id: true } }));
          break;
        case 'DocumentSubmission':
          exists = !!(await prisma.documentSubmission.findUnique({ where: { id: wu.referenceId }, select: { id: true } }));
          break;
        case 'AssemblyPart':
          exists = !!(await prisma.assemblyPart.findUnique({ where: { id: wu.referenceId }, select: { id: true } }));
          break;
        case 'WeldingInspection':
          exists = !!(await prisma.weldingInspection.findUnique({ where: { id: wu.referenceId }, select: { id: true } }));
          break;
        default:
          exists = false;
      }
    } catch {
      exists = false;
    }

    if (!exists) {
      await prisma.workUnit.delete({ where: { id: wu.id } });
      orphanedCount++;
    }
  }
  console.log(`✓ Deleted ${orphanedCount} orphaned WorkUnits`);

  // 4. Clear seeded ResourceCapacity (optional - keep if you want to preserve manually created ones)
  // Uncomment the following if you want to clear all resource capacities:
  // const deletedResources = await prisma.resourceCapacity.deleteMany({});
  // console.log(`✓ Deleted ${deletedResources.count} ResourceCapacities`);

  console.log('\n═══════════════════════════════════════════════════════');
  console.log('✅ Seeded data cleared successfully!');
  console.log('\nThe Operations Control dashboard should now be empty.');
  console.log('Real data will appear when you:');
  console.log('  1. Create Tasks, WorkOrders, RFIs, or DocumentSubmissions');
  console.log('  2. The Early Warning Engine runs (hourly) to detect risks');
  console.log('═══════════════════════════════════════════════════════');
}

main()
  .catch((e) => {
    console.error('❌ Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
